import React from "react"
import { Transition } from "@headlessui/react"

export function CollapsableSection(props) {
    const [isOpen, setIsOpen] = React.useState(false)

    return (
        <div className="pt-6">
            <dt className="text-lg">
                <button className="text-left w-full flex justify-between items-start text-gray-400" onClick={() => setIsOpen(!isOpen)}>
                    <span className="font-medium text-gray-900">
                        {props.title}
                    </span>
                    <span className="ml-6 h-7 flex items-center">
                        <svg className={`${isOpen ? '-rotate-180': '-rotate-0'} h-6 w-6 transform`} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                        </svg>
                    </span>
                </button>
            </dt>
            <Transition
                show={isOpen}
                enter="transition ease-out duration-100 transform"
                enterFrom="opacity-0 scale-95"
                enterTo="opacity-100 scale-100"
                leave="transition ease-in duration-75 transform"
                leaveFrom="opacity-100 scale-100"
                leaveTo="opacity-0 scale-95"
            >
                <dd className="mt-2 pr-12">
                    <p dangerouslySetInnerHTML={{__html: props.text}} className="text-base text-gray-500"/>
                </dd>
            </Transition>
        </div>
    )
}

export const HOME_FAQS = [
    {
        title: "What are shares?",
        text: "Shares on the Realium platform are Non-Fungible Tokens that represent debt or equity in a specific real estate asset. The value of a share is largely determined by the income and capital appreciation associated with owning a property. Income on the property is generated by  rental income (less operating expenses such as property tax, insurance, maintenance, and mortgage debt). Because shares are pegged to a real world asset, they appreciate as the value of the property increases over time. Ultimately, the value is determined by the buyer demand which can surpass both of these figures."
    },
    {
        title: "What are the costs associated with the platform?",
        text: `In order for a purchase or sale to go through, a transaction fee is required to add that transaction to the blockchain. The current transaction fees are based on the different functions performed on the Realium platform and range from 0.001 AVAX to 0.01 AVAX. For a full list of the transactions fees, please refer to the <a target="_blank" rel="noreferrer" href="https://docs.avax.network/learn/platform-overview/transaction-fees">Avalanche Fee Schedule.</a>`
    },
    {
        title: "What is the difference between buying, selling, and offering?",
        text: "Users are able to buy shares of a property that have been listed for sale. These shares are owned by another Realium user that has set a specific asking price and a specific quantity. If users do not see any available shares at their desired price and quantity, they can submit an offer to purchase. Offers are binding and require users to lock up funds when submitting the offer. When a user wants to sell shares of their property, they are able to list the sale price and desired quantity. This allows for users to control the price while Realium only aggregates the historical transaction data to produce transaction trends on specific properties."
    },
    {
        title: "How and when do properties get added?",
        text: "Properties are added by the Realium team on a rolling basis. Please subscribe to our newsletter to be notified when new properties are added to the platform. Shares are bought very quickly when new assets are added, thus 80% of the shares will be available and launched and a remaining 20% of the shares will be available 12 hours after the property is listed."
    }
]

export const HOW_IT_WORKS_FAQS = [
    {
        title: "What is AVAX?",
        text: `AVAX is the currency used on the Realium platform and is noted by the (SYMBOL). By clicking the wallet amount in the top right corner of your account, you can switch between AVAX and USD. AVAX as its own currency will fluctuate in value over time. Click <a target="_blank" rel="noreferrer" href="https://coinmarketcap.com/currencies/avalanche/">here</a> to view a historic price of AVAX.`
    },
    {
        title: "What are my investor rights?",
        text: "All Realium investors represent a single line on your cap table and act as a single investor—without voting or information rights. This means there is no limit to the amount of investors who can participate in trading a property."
    },
    {
        title: "What are my ownership rights to the property?",
        text: "Buying shares of a property on the Realium platform is completely independent of landlord rights to live in the property. Furthermore, investors do not participate in the management of the property. All Realium properties are managed by external teams. As an investor in the property, you own shares in the property that can be sold at any time at your specified price."
    },
    {
        title: "What is the difference between buying, selling, and offering?",
        text: "Users are able to buy shares of a property that have been listed for sale. These shares are owned by another Realium user that has set a specific asking price and a specific quantity. If users do not see any available shares at their desired price and quantity, they can submit an offer to purchase. Offers are binding and require users to lock up funds when submitting the offer. When a user wants to sell shares of their property, they are able to list the sale price and desired quantity. This allows for users to control the price while Realium only aggregates the historical transaction data to produce transaction trends on specific properties."
    }
]

export const MARKETPLACE_FAQS = [
    {
        title: "What are the differences between the property types on the platform?",
        text: "Properties are categorized into residential and commercial opportunities. Residential properties focus on single family, multifamily, condo, etc. Commercial properties that are used exclusively for business-related purposes or to provide a workspace rather than as a living space. Examples of commercial properties include office space, industrial space, retail space."
    },
    {
        title: "How are properties managed?",
        text: "AAll Realium properties are managed by external management companies. These companies ensure that the property is rented out, cover basic maintenance, and collect rent."
    },
    {
        title: "Who owns the properties on the platform?",
        text: "Properties on the Realium platform are owned by private investors. Portions of the asset are added to the platform through tokenization, allowing the owners to have immediate access to their capital."
    }
]

export const ACCOUNT_FAQS = [
    {
        title: "How do I add funds to my wallet?",
        text: `While Realium is in beta, funds are added through the <a target="_blank" rel="noreferrer" href="https://faucet.avax-test.network/">Avalanche Test Faucet</a>. By copying your account’s wallet address, you are able to add funds to your account. The faucet allows you to add 2 AVAX at a time. AVAX is the currency used on the Realium platform and is noted by the (SYMBOL) symbol throughout the site.`
    },
    {
        title: "What are my investor rights?",
        text: "All Realium investors represent a single line on your cap table and act as a single investor—without voting or information rights. This means there is no limit to the amount of investors who can participate in trading a property."
    },
    {
        title: "What are my ownership rights to the property?",
        text: "Buying shares of a property on the Realium platform is completely independent of landlord rights to live in the property. Furthermore, investors do not participate in the management of the property. All Realium properties are managed by external teams. As an investor in the property, you own shares in the property that can be sold at any time at your specified price."
    }
]
